### PR TITLE
match domain names faster

### PR DESCRIPTION
**Pull request by pcmid**
When the domain file is large, the match will get faster and le.com will never match google.com again.

### CODE REVIEW

**Comment by shawn1m** [comment]
Thank you for your PR!
The current domain matching uses regex, `le.com` will match `google.com` indeed. However, it's possible to use regex metacharacter to create a custom pattern to match `le.com` only.

I think it would be better to let people choose their own matching policy instead of simply replace the current regex implementation, and it would be nice if the current regex matching for domain and hosts could be faster.

**Comment by pcmid** [comment]
Thank you for reply.

In my opinion, the matching speed is the most important. I have a list
of 50,000 rows of domains. It is really too slow to use regular
matching. So I submitted this pr. A more precise match is a side
effect on this.


Shawn <notifications@github.com> 于2019年3月16日周六 下午10:14写道：

**Comment by shawn1m** [comment]
I suppose it's better to make both strategies exist and let people choose their own way. 

I will merge it sometime later after I found a proper solution.

**Comment by shawn1m** [comment]
Merged. Thanks!

**Pull request merged**
