### PR TITLE
Update build.py

### PR DESCRIPTION
**Pull request by everfly**
1. Windows file add `.exe`
2. add noGUI version on windows as discussed https://github.com/shawn1m/overture/issues/4
2. add GOARM value

### CODE REVIEW

**Comment by shawn1m** [comment]
First of all, thank you very much for your contribution.
1. I think there is no need for windows file to add `.exe`, because overture is only available when used in cmd.
2. As discussed in #4, the problem I concerned most is the user experience. Native windows gui is much better than default noGUI of Go. People can compile their own binary if needed.
3. Accepted.
There is little code revision you could make, please refer to the code comment I make.

**Comment by everfly** [comment]
Ok, Thanks for your comment.
Personally I think noGUI version is better for add to auto startup, cuz once your configuration done well, all you need is to run the service in background, silently, only few people need to use verbose mode to debug.
For the `.exe`, I think it is a real need for windows users, on Windows, I belive only few people use cmd.

Thanks anyway, I'll just keep these changes in my fork and close this pull request

**Comment by shawn1m** [comment]
At first, I also added `.exe` this way, but then I realized people would like to try to run it with double click, and we all know it will take no effect. In order to avoid this confusion, I delete the `.exe` to make people run overture on cmd. Maybe I should have made it clear in README.

**Comment by shawn1m** [comment]
Oh, I find the main problem is that there is no chance to run program without `.exe` on cmd ......
I must replace the release package as soon as possible ......
Thanks a lot for your inspiration and help.
0aabdf373ac576c2a476963b9881dd831f20f415

**Comment by everfly** [comment]
> no chance to run program without .exe on cmd

Didn't notice this problem too! LOL

> At first, I also added .exe this way, but then I realized people would like to try to run it with double click, and we all know it will take no effect.

With all the configuration files well configured in the zip file , I think just double click the `.exe` file will take effect.(just put `exe` file, `china_ip_list`, `config.json`, `gfwlist`, `host` in the same folder)  No need to run in cmd. So that's why I said using noGUI version to auto startup is better choice for Windows version

**Comment by everfly** [comment]
还是中文解释下noGUI的好处（和作者的观点不同，不过胜在方便）：
首先下载release中的`overture-windows-386.zip`或`overture-windows-amd64.zip`,解压缩到某个位置，比如`C:\overture`，然后根据实际情况配置好`config.json`，此时直接双击运行`overture-windows-386.exe`打开的便是等效的cmd打开的`overture-windows-386.exe -c config.json`，但是这样会有一个黑框GUI界面显示，不能关掉，这时有noGUI版本的好处就体现出来了，直接后台运行，只要配置文件没有错误就能正常解析了。
本地网络设置DNS解析为127.0.0.1，如果开机忘了启动overture，那么这时不能正常访问网页，所以需要overture开机自动启动，但是如果开机启动弹出来一个黑狂的overture-windows-386的界面，也不美观，所以需要用到noGUI版本了，LOL
Windows 10设置开机启动：`Win键+R`，输入`shell:startup`,然后把noGUI版本快捷方式拖进去就好了，这样就做到了开机自启动不影响任何使用不影响桌面美观了
建议windows release版本中同时放入普通版本和noGUI版本，即方便调试也方便使用。目前个人是这样使用的了。
最后最后，感谢作者提供这个overture，目前感觉很好用LOL

**Comment by shawn1m** [comment]
😄 的确是可以直接点的，只要路径合适。

**Pull request closed without merging**
