### PR TITLE
Host file support one domain have ipv4 and ipv6 same time (#185)

### PR DESCRIPTION
**Pull request by SharerMax**

### CODE REVIEW

**Comment by shawn1m** [comment]
Thanks for your PR!
Please explain the idea of your code in few words, I'm a little bit confused.
In my point of view, I think the check existing and add method must be reimplement if let the hosts feature of overture to support ipv4 and ipv6 at the same time...

**Comment by SharerMax** [comment]
Sorry. 

``` Go
type hostsLine struct {
	domain string
	ip     net.IP
	ipv6   bool
}
```
when execute `parseLine` function, `ipv6` has been set.  so if ip is ipv4 the `ipv6` is `false` and if ip is ipv6 the `ipv6` is `true`. 

I think `domain` and `ipv6` indicate one unique host record. so we can compare `domain` and `ipv6` to determine host reocrd whether exist or not exist.

**Comment by shawn1m** [comment]
Merged. It seems work, I will check it when I have enough time. 
Thanks!

**Comment by SharerMax** [comment]
I have a lite confused thing about ```ipv6``` field. Why use ```ip.to4()``` or ```ip.to6()``` to detaermine ip type not ```ipv6``` field in ```FindHosts```([code link](https://github.com/SharerMax/overture/blob/88d0adceb50fd20f8b2cabc2ca57e6d5ee77cd83/core/hosts/line.go#L66)) method?

**Pull request merged**
