### PR TITLE
Support build android and ios executables

### PR DESCRIPTION
**Pull request by NyaMisty**
Mobile build with test

Change to ubuntu + mac

Fix build.py

Fix android build

Cleanup the appveyor.yml

### CODE REVIEW

**Comment by NyaMisty** [comment]
I've changed the skip_branch_with_pr and skip_tag option.
As the appveyor build now builds more platforms, we should make it build every commit.
Also many PR has some feature needs to be tested, and providing them a safe and accessible binary test build will make everyone happy :)

**Comment by shawn1m** [comment]
What are these android and ios builds actually for?

**Comment by NyaMisty** [comment]
Well users can run binaries on iOS if they jailbreaked, and android user
can use the overture in termux. Android and iOS do lack a good DNS
dispatcher, and most vpn software solution can't uses the DoT and DoH, so
some users need overture. And I've also tested the iOS compiled binary,
which works flawlessly on my device.

**Comment by shawn1m** [comment]
Merged. Thanks!

**Pull request merged**
